# Análisis de refuerzos — Chaco For Ever

Buscador de datos de los nuevos refuerzos. **Pegás el link de Transfermarkt** del
jugador y el notebook arma su ficha: bio, a qué clubes perteneció y cómo venía
jugando (partidos, goles, asistencias, minutos por competición).

**Cómo se usa**
1. En la celda de *Refuerzos*, pegá el/los link(s) de Transfermarkt (nombre → URL).
2. Menú *Run → Run All*.
3. Mirá las fichas más abajo. Se guardan en `outputs/refuerzos/`.

> La primera vez abre un navegador y baja los datos (con demoras para no ser
> bloqueado). Después usa el cache en `data/refuerzos/{id}/` y es instantáneo.
>
> Ojo: aunque el jugador ya sea **refuerzo confirmado**, Transfermarkt puede
> mostrarlo todavía como *Sin equipo* o en su club anterior. Es normal.

In [1]:
import sys, os
from pathlib import Path
# raíz del proyecto en el path
ROOT = Path.cwd()
if not (ROOT / 'src').exists() and (ROOT.parent / 'src').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

import pandas as pd
from IPython.display import Markdown, display
from src.scraping.transfermarkt_scraper import fetch_player, resumen_texto
import config
print('OK · delays SofaScore/Transfermarkt:', config.MIN_DELAY, '-', config.MAX_DELAY, 's')

OK · delays SofaScore/Transfermarkt: 6 - 12 s

## 1) Refuerzos a analizar

Editá este diccionario: **nombre → link de Transfermarkt**. Podés poner varios.
El de Matías Romero queda de ejemplo.

In [2]:
REFUERZOS = {
    "Matías Romero": "https://www.transfermarkt.com.ar/matias-romero/profil/spieler/853464",
    "Leandro Fernandez": "https://www.transfermarkt.com.ar/leandro-fernandez/profil/spieler/355904",
    "Federico Moreno": "https://www.transfermarkt.com.ar/federico-moreno/profil/spieler/1139701",
    "Mauricio Tevez": "https://www.transfermarkt.com.ar/mauricio-tevez/profil/spieler/334097",
    # "Otro Refuerzo": "https://www.transfermarkt.com.ar/.../profil/spieler/XXXXX",
}

## 2) Bajar y parsear

Usa cache: si ya bajaste al jugador, no vuelve a la web. Para forzar una nueva
bajada, borrá su carpeta en `data/refuerzos/{id}/` o pasá `use_cache=False`.

In [3]:
fichas = {}
for nombre, url in REFUERZOS.items():
    try:
        fichas[nombre] = fetch_player(url, use_cache=True)
        print(f'✓ {nombre}')
    except Exception as e:
        print(f'✗ {nombre}: {e}')
print(f'\n{len(fichas)} ficha(s) lista(s).')

✓ Matías Romero
✓ Leandro Fernandez
✓ Federico Moreno
✓ Mauricio Tevez

4 ficha(s) lista(s).

## 3) Fichas

In [4]:
for nombre, f in fichas.items():
    display(Markdown(resumen_texto(f)))
    display(Markdown('**Trayectoria (con vueltas):** ' + ' → '.join(f['trayectoria'])))
    display(pd.DataFrame(f['carrera']))
    display(Markdown('---'))

# Matías Romero  (Matías Sebastián Romero)
- **Rol:** Delantero centro  (ficha: Delantero - Delantero centro)
- Pie: Derecho · Altura: 1,85 m
- Nacimiento: 06/06/1994 (32) · Formosa (Argentina)
- Valor de mercado: 200 mil € · Club en TM: Sin equipo
- Clubes: Unión Güemes → Patria → Juv. Unida (SL) → Chaco For Ever → Dep. Morón → Nueva Chicago
- Carrera: 176 PJ · 29 goles · 8 asistencias · 10015 min
- **Último club — Nueva Chicago (2026):** 15 PJ · 639 min · 42.6′/PJ · 1 goles → **Poco rodaje: mayormente suplente**

| Competición | PJ | Goles | Asist. | Minutos |
|---|---:|---:|---:|---:|
| Primera Nacional | 129 | 21 | 6 | 7345 |
| Torneo Federal A | 34 | 6 | 2 | 2037 |
| Copa Argentina | 8 | 1 | - | 310 |
| Torneo Fed. A Playoff | 4 | 1 | - | 312 |
| Prim. Nacional - Reducido | 1 | - | - | 11 |

**Últimas temporadas** (año · competición):

| Año | Competición | PJ | Goles | Asist. | Minutos |
|---|---|---:|---:|---:|---:|
| 2026 | Primera Nacional | 15 | 1 | - | 639 |
| 2025 | Primera Nacional | 32 | 11 | 3 | 2512 |
| 2024 | Primera Nacional | 33 | 1 | 1 | 1570 |
| 2023 | Primera Nacional | 28 | 7 | - | 1593 |
| 2023 | Copa Argentina | 3 | - | - | 136 |
| 2022 | Prim. Nacional - Reducido | 1 | - | - | 11 |

**Trayectoria (con vueltas):** Unión Güemes → Patria → Juv. Unida (SL) → Chaco For Ever → Dep. Morón → Chaco For Ever → Nueva Chicago

                 competicion  partidos  goles  asistencias  minutos
0           Primera Nacional       129   21.0          6.0     7345
1           Torneo Federal A        34    6.0          2.0     2037
2             Copa Argentina         8    1.0          NaN      310
3      Torneo Fed. A Playoff         4    1.0          NaN      312
4  Prim. Nacional - Reducido         1    NaN          NaN       11

---

# Leandro Fernández  (Leandro David Fernández)
- **Rol:** Extremo izquierdo  (ficha: Delantero - Extremo izquierdo)
- Pie: Izquierdo · Altura: 1,81 m
- Nacimiento: 23/01/1995 (31) · Almafuerte (Argentina)
- Valor de mercado: ? · Club en TM: CA Chaco For Ever
- Clubes: Belgrano S20 → Belgrano II → Crucero → Guillermo Brown → Sp. Las Parejas → Racing (Cba) → Villa Mitre → Chaco For Ever
- Carrera: 10 PJ · None goles · None asistencias · 900 min
- **Último club — Chaco For Ever (2026):** 10 PJ · 900 min · 90.0′/PJ · 0 goles → **Titular habitual**

| Competición | PJ | Goles | Asist. | Minutos |
|---|---:|---:|---:|---:|
| Torneo Federal A | 10 | - | - | 900 |

**Últimas temporadas** (año · competición):

| Año | Competición | PJ | Goles | Asist. | Minutos |
|---|---|---:|---:|---:|---:|
| 2026 | Torneo Federal A | 10 | - | - | 900 |
| 2025 | Primera Nacional | 34 | 2 | 1 | 2600 |
| 2025 | Copa Argentina | 1 | - | - | 90 |
| 2024 | Prim. Nacional - Reducido | 1 | - | - | 90 |
| 2024 | Primera Nacional | 35 | 2 | 4 | 2890 |
| 2023 | Primera Nacional | 33 | 2 | 3 | 2910 |

**Trayectoria (con vueltas):** Belgrano S20 → Belgrano II → Crucero → Belgrano II → Guillermo Brown → Belgrano II → Sp. Las Parejas → Racing (Cba) → Villa Mitre → Chaco For Ever

        competicion  partidos goles asistencias  minutos
0  Torneo Federal A        10  None        None      900

---

# Federico Moreno  (Federico Esequiel Moreno)
- **Rol:** Defensa central  (ficha: Defensa - Defensa central)
- Pie: Derecho · Altura: 1,90 m
- Nacimiento: 23/02/2001 (25) · Córdoba (Argentina)
- Valor de mercado: 25 mil € · Club en TM: Círculo Deportivo
- Clubes: Crucero U19 → Crucero II → Crucero → Circulo Dep. → General Paz Jrs → Dep. Rincón → Nueva Chicago
- Carrera: 3 PJ · None goles · None asistencias · 237 min
- **Último club — Circulo Dep. (2026):** 3 PJ · 237 min · 79.0′/PJ · 0 goles → **Titular habitual**

| Competición | PJ | Goles | Asist. | Minutos |
|---|---:|---:|---:|---:|
| Primera Nacional | 3 | - | - | 237 |

**Últimas temporadas** (año · competición):

| Año | Competición | PJ | Goles | Asist. | Minutos |
|---|---|---:|---:|---:|---:|
| 2026 | Primera Nacional | 3 | - | - | 237 |
| 2025 | Federal A - Reválida Playoff | 4 | - | - | 340 |
| 2025 | Torneo Fed. A Playoff | 2 | - | - | 180 |
| 2025 | Federal A - Fase Campeonato | 8 | - | - | 709 |
| 2025 | Torneo Federal A | 17 | 1 | - | 1404 |
| 2024 | Federal A - Fase Reválida | 8 | - | - | 720 |

**Trayectoria (con vueltas):** Crucero U19 → Crucero II → Crucero → Circulo Dep. → General Paz Jrs → Circulo Dep. → Dep. Rincón → Circulo Dep. → Nueva Chicago → Circulo Dep.

        competicion  partidos goles asistencias  minutos
0  Primera Nacional         3  None        None      237

---

# #20 Mauricio Tévez  (Mauricio Alejandro Tévez)
- **Rol:** Extremo derecho  (ficha: Delantero - Extremo derecho)
- Pie: Derecho · Altura: 1,70 m
- Nacimiento: 31/07/1996 (29) · Rosario (Argentina)
- Valor de mercado: 25 mil € · Club en TM: AA Estudiantes (Río Cuarto)
- Clubes: Newell's U20 → Newell's → Instituto ACC → Def. y Justicia → AD Oliveirense → Luqueño → Guaireña FC → Chacarita Jrs. → Douglas Haig → Estudiantes RC
- Carrera: 3 PJ · None goles · None asistencias · 113 min
- **Último club — Estudiantes RC (2024-2026):** 27 PJ · 830 min · 30.7′/PJ · 0 goles → **Poco rodaje: mayormente suplente**

| Competición | PJ | Goles | Asist. | Minutos |
|---|---:|---:|---:|---:|
| Torneo Apertura | 2 | - | - | 36 |
| Copa Argentina | 1 | - | - | 77 |

**Últimas temporadas** (año · competición):

| Año | Competición | PJ | Goles | Asist. | Minutos |
|---|---|---:|---:|---:|---:|
| 2026 | Torneo Apertura | 2 | - | - | 36 |
| 2026 | Copa Argentina | 1 | - | - | 77 |
| 2025 | Primera Nacional | 8 | - | - | 222 |
| 2024 | Primera Nacional | 16 | - | - | 495 |
| 2023 | Asc. Fed. A & Prim. B Metro | 1 | - | - | 56 |
| 2023 | Torneo Fed. A Playoff | 4 | - | - | 251 |

**Trayectoria (con vueltas):** Newell's U20 → Newell's → Instituto ACC → Newell's → Def. y Justicia → Newell's → AD Oliveirense → Luqueño → Guaireña FC → Chacarita Jrs. → Douglas Haig → Estudiantes RC

       competicion  partidos goles asistencias  minutos
0  Torneo Apertura         2  None        None       36
1   Copa Argentina         1  None        None       77

---

## 4) Guardar las fichas

Guarda un `.md` por jugador y un `.json` con todo, en `outputs/refuerzos/`.
Esto es lo que después alimenta la placa de Instagram del refuerzo.

In [5]:
import json, re, unicodedata
OUT = Path('outputs/refuerzos'); OUT.mkdir(parents=True, exist_ok=True)
def _slug(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()
    return re.sub(r'[^a-z0-9]+', '_', s.lower()).strip('_')
for nombre, f in fichas.items():
    slug = _slug(nombre)
    (OUT / f'{slug}.md').write_text(resumen_texto(f), encoding='utf-8')
    (OUT / f'{slug}.json').write_text(json.dumps(f, ensure_ascii=False, indent=2), encoding='utf-8')
    print('guardado:', OUT / f'{slug}.md')

guardado: outputs\refuerzos\matias_romero.md
guardado: outputs\refuerzos\leandro_fernandez.md
guardado: outputs\refuerzos\federico_moreno.md
guardado: outputs\refuerzos\mauricio_tevez.md

---
Con la ficha lista (`outputs/refuerzos/*.json`) se puede armar el carrusel del
refuerzo en `redes_sociales/instagram/` reusando las placas `portada_jugador`,
`ficha`, `chips` y `dato`, igual que el carrusel *Vuelve Matías Romero*.